-- Pokemon Music Quiz Database Setup
-- Execute these queries in your Supabase SQL Editor

-- Enable RLS on tracks table
ALTER TABLE public.tracks ENABLE ROW LEVEL SECURITY;

-- Tracks policies (public read access)
CREATE POLICY tracks_select_policy ON public.tracks 
FOR SELECT USING (true);

-- Favorites table
CREATE TABLE IF NOT EXISTS public.favorites (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  track_title text null,
  game_name text null,
  generation text null,
  user_id uuid null default auth.uid(),
  constraint favorites_pkey primary key (id)
);

-- Enable RLS on favorites table
ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;

-- Favorites policies
CREATE POLICY favorites_select_policy ON public.favorites 
FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY favorites_insert_policy ON public.favorites 
FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY favorites_delete_policy ON public.favorites 
FOR DELETE USING (auth.uid() = user_id);

-- User stats table
CREATE TABLE IF NOT EXISTS public.user_stats (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  total_plays bigint null,
  correct_answers bigint null,
  best_streak bigint null,
  user_id uuid null default auth.uid(),
  constraint user_stats_pkey primary key (id)
);

-- Enable RLS on user_stats table
ALTER TABLE public.user_stats ENABLE ROW LEVEL SECURITY;

-- User stats policies
CREATE POLICY user_stats_select_policy ON public.user_stats 
FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY user_stats_insert_policy ON public.user_stats 
FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY user_stats_update_policy ON public.user_stats 
FOR UPDATE USING (auth.uid() = user_id);